### ISSUE TITLE
NOT Working

### ISSUE THREAD

**Issue by YChen7913** [Giingu/DiscordPlus#10]
Hi, is this still working? Nothing happen for me after installation.

**Comment by kckarnige** [comment]
I'm pretty sure this project was abandoned a while ago :/

**Comment by kckarnige** [comment]
I recommend GooseMod if you're still interested in anything here, and maybe use Discord PTB for the account switcher functionality since that's going being added soon to Discord

**Comment by FoxsCode** [comment]
Hi there, yes the project is currently dead because I had no time to work on it, I do plan on giving the torch to someone else so they can continue with it.

Currently, I'm a student and also have a job so I don't have much free time, i've worked on it a bit from time to time tho, and so far I got it to work again and also was able to successfully turn it into a great extension where you can enable and disable functionalities!

**Comment by YChen7913** [comment]
> Hi there, yes the project is currently dead because I had no time to work on it, I do plan on giving the torch to someone else so they can continue with it.
> 
> Currently, I'm a student and also have a job so I don't have much free time, i've worked on it a bit from time to time tho, and so far I got it to work again and also was able to successfully turn it into a great extension where you can enable and disable functionalities!

**Comment by YChen7913** [comment]
> > Hi there, yes the project is currently dead because I had no time to work on it, I do plan on giving the torch to someone else so they can continue with it.
> > Currently, I'm a student and also have a job so I don't have much free time, i've worked on it a bit from time to time tho, and so far I got it to work again and also was able to successfully turn it into a great extension where you can enable and disable functionalities!

Hi I feel sorry that I can't help. However, I'am looking forward to the extension!!!

**Comment by Giingu** [comment]
DiscordPlus+ is now back!

**Comment by Giingu** [comment]
DiscordPlus+ is now back!
