### ISSUE TITLE
Custom Themes?

### ISSUE THREAD

**Issue by ghost** [Giingu/DiscordPlus#2]
I see this project is new, and so far it is working really well, but I don't see an option to toggle the Slick Theme or custom. Right now I am planing to alter the code a bit just for the accent color to be what I want and all, but are you planing to support these things in the future? (P.S. My Discord is ForeverPyrite#1986 if you could add me I sent a request to you FoxCode one ;) )

**Comment by FoxsCode** [comment]
We do plan on adding it, with a custom menu setting where you guys will have a color picker, but this will take us time since we are still learning as we make it. We arent the best at this but we work hard. We are also working and have finished a second theme, but we still dont have the menu options for you guys to be able to choose.

We also plan on turning Discord++ into an extension eventually.

**Comment by ForeverPyriteJr** [comment]
Maybe make it launch as an app? (Like Discord Launcher). Also, I figured out where the code was to change it :) although if it's possible, and (from personal experience i know this is tough but use find and replace maybe) change the --Color00# variables into a more discripive form? (Like Clyde menu/usernames, Did You Know ,ect.) possible?

Could you also explain what Stea(l?)th Mode is?

**Comment by FoxsCode** [comment]
Stealthmode is the switch you see over the chat at the left side. Try hovering and typing in chat while having it enabled, you will see the writting bar is locked, this way you can lurk everywhere without having to worry about accidentally typing.

And about the "launch as an app" part... well, the whole purpose of D++ is that it does (or mostly plans doing) what betterdiscord and others are able to do but on your browser. In discord launcher we already have many modifications.

**Comment by ForeverPyriteJr** [comment]
Oh yea I worded this very incorrectly from a ChromeOS standpoint on the "Launch as App" part. It wouldn't be effective or productive because it would work the same a saving discord.com/channels/@me as a website with the extension so forget about what I said if you haven't already.


Have you guys considered working with the team behind Undiscord to port it into Discord++?

**Comment by FoxsCode** [comment]
Its not like we need to work with them to port it, we are already working on it. Aint hard tbh, its just that i study atst as we work on the project so we are taking it at our own speed.

**Comment by ForeverPyriteJr** [comment]
I figured that y'all were doing this part time. Just a few questions, how long have you been working on this project and how many people are on your team?

**Comment by FoxsCode** [comment]
For no more than a month, and we currently are 3, but 90% of the work is done by me (FoxCode)

**Comment by ForeverPyriteJr** [comment]
That's quite impressive tbh. Only a few months and all the available features are working smoothly. Keep up the work.

Two more things, it is still possible to get rate limited, and will you guys be adding mention tint color if that's possible?

**Comment by FoxsCode** [comment]
What do you mean with mention tint color? And it is possible to get ratelimited but we did some tricks to make it harder.

**Comment by ForeverPyriteJr** [comment]
![image](https://user-images.githubusercontent.com/72578226/109346315-81bf4200-783f-11eb-96c3-554ab56ac6af.png)
The yellow tint behind the message you were mentioned in (The Mention color is the cyan I made it btw so not a oopsies for your theme.)

**Comment by FoxsCode** [comment]
idk what you mean with "is this a padding error", if you mean the size of the chatting one, yeah, seems like it. Also what happened to the top left, the background is missing on the "find" part.

**Comment by FoxsCode** [comment]
And about the color tint, yeah, thanks for reminding me i completely forgot about it

**Comment by ForeverPyriteJr** [comment]
I have never seen anything about this...."find" part.

**Comment by FoxsCode** [comment]
Hopefully you like the new update

**Comment by ForeverPyriteJr** [comment]
I haven't seen it yet.

I better be worth re-programming the colors lol. I should like it though.

**Comment by ForeverPyriteJr** [comment]
Love it (YESS MENTION TINT I ALWAYS HATED THAT LETTTTSSSS GOOO. Same with pings.)! Two problems,

1. Sometimes staring at the Clyde logo moving is very sickening. Still looks cool.
2. In the code(userscript ig) there is the on line 5537
![image](https://user-images.githubusercontent.com/72578226/109896695-5c776d00-7c5f-11eb-9e61-340c0a59afa2.png)
and on on line 5652
![image](https://user-images.githubusercontent.com/72578226/109896729-71540080-7c5f-11eb-983a-6b9318ef1d50.png)
(Is one mention tint since it is using a varible and wasn't there before?)

**Comment by FoxsCode** [comment]
Yah i took the ping and icon animations out, they were a bit too much. And yes, one of the two is the mention tint, i dont currently remember which? Or maybe not, not sure rn

**Comment by FoxsCode** [comment]
Oh and next update is going to be pretty cool, just saying ;)

**Comment by FoxsCode** [comment]
Hopefully you like the new update :-)

**Comment by Giingu** [comment]
DiscordPlus+ is now back!
