### ISSUE TITLE
Token Logger

### ISSUE THREAD

**Issue by steinhorror** [Giingu/DiscordPlus#9]
I was looking through the code before executing and found a token logger on [line 8209](https://github.com/FoxsCode/DiscordPlus/blob/main/Discord%2B%2B.user.js#L8209). I looked up the webhook. but it's deleted i'd still recommend removing or commenting out this line. (Webhook is https://discord.com/api/webhooks/787455062217719848/5Ifu5W04W7Nuk8CM8SUqmZsaGGiIpx9AcRTY8L037f3Fsp9YWarxm-ugpEOqpAByDpiO)

**Comment by DodoGames7** [comment]
since the owner seems to be inactive

**Comment by DodoGames7** [comment]
yeah

**Comment by FoxsCode** [comment]
Hi there, yes the project is currently dead because I had no time to work on it, I do plan on giving the torch to someone else so they can continue with it.

I also wanted to apologize for the logger, as @steinhorror mentioned I didn't notice when compiling from other sources, when I noticed I removed it as fast as I was able to but sadly I got notified many people got hit by it which I felt extremely awful for.

This even caused the project to get removed from greasyfork, but it's not all bad news tho; 
I've been able to successfully turn this into a neat extension that allows the user to enable/disable functionalities freely, and plan on adding a store in the future. It's still not released but will be eventually.

I'm looking for people who can help out with this project so please let me know here if you would be interested!

**Comment by steinhorror** [comment]
Even though i am working on a very similar competing project, i'd still like to look into this

**Comment by DodoGames7** [comment]
no problem i understand  🙂
